baseURL = 'https://mzo.kuku9.net/'
languageCode = 'ja-JP'

disableKinds = ["taxonomy", "sitemap", "RSS"]
disableSitemap = true

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false


[languages]
  [languages.ja]
    languageCode = "ja"
    title = "AIはあなたを自由にするか？"
    [languages.ja.params]
        subtitle = "CASUAL ver."
        description = "AIはあなたを自由に\"しない\"であろう理由を簡潔にまとめました"
        cardFilename = "card_image.png"

   [languages.en]
      languageCode = "en"
      title = "Will A.I. set you free"
      [languages.en.params]
        subtitle = "CASUAL ver."
        description = "The reason why A.I. will not set you free"
        cardFilename = "card_image.en.png"
     [languages.en.markup.goldmark.extensions.cjk]
         enable = false
     [languages.en.markup.goldmark.renderer]
         unsafe = true

[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.cjk]
        enable = true
        eastAsianLineBreaks = true
        eastAsianLineBreaksStyle = 'css3draft'

    [markup.goldmark.renderer]
      unsafe = true
